default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sport_up_development

test:
  <<: *default
  database: sport_up_test

production:
  <<: *default
  database: sport_up_production
