default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sport_up_database

test:
  <<: *default
  database: sport_up_database

production:
  <<: *default
  database: sport_up_database
